### ISSUE TITLE
timestamps issue?

### ISSUE THREAD

**Issue by Legit4K** [Romejanic/slasher#1]
**Describe the bug**
Using slasher, I'm unable to access the `createdTimestamp` property from a reply.

**To Reproduce**
```js
    async execute(ctx, client) {
        let wait = await ctx.reply(`\`pinging...\``);

        let ping = new MessageEmbed()
            .setTitle("BOT LATENCY / PING")
            .setColor("RANDOM")
            .addField("Response Time", `${wait.createdTimestamp - ctx.createdTimestamp}ms`)
            .addField("API Latency", `${Math.round(client.ws.ping)}ms`)
        await ctx.edit(ping);
    }
```

**Expected behavior**
Using discord.js interactions, I would be able to access the timestamp of an interaction reply. I can't do that here 🤔

**Screenshots**
none

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.5
 - Node Version: 16.10.0
 - Language: Javascript

**Additional context**
```
TypeError: Cannot read properties of undefined (reading 'createdTimestamp')
```

**Comment by Romejanic** [comment]
Please refer to the [CommandContext](https://github.com/Romejanic/slasher/blob/master/docs/api/CommandContext.md) docs.

`ctx` isn't the interaction itself, it's a context object with information about it. To access that field you'll need to use `ctx.command.createdTimestamp`.

**Comment by Legit4K** [comment]
Yeah, I tried that too same issue (it can be accessed through `ctx.command` but not from `wait` whereas through the native interactions api in discord.js it can be done using `wait.createdTimestamp`)

**Comment by Legit4K** [comment]
I've discovered an alternative way to measure the ping so it's not a big deal I suppose
